### ISSUE TITLE
axis2-1.7.8/bin/wsdl2java.sh doesn't like mobileid.wsdl

### ISSUE THREAD

**Issue by ralfhauser** [phaupt/mobileid-java#1]
Great samples.
Unfortunately lot's of libraries I don't use yet.
So I tried to run axis2-1.7.8/bin/wsdl2java.sh on
  https://github.com/phaupt/mobileid-java/blob/master/client-cxf-jaxws/mobileid.wsdl 
unfortunately, this turns out not to be that successful:

Retrieving document at 'file:///home/memobileId/mobileid.wsdl'.
[WARN] No schemaLocation for import of http://www.w3.org/2000/09/xmldsig#; compilation may fail
[WARN] No schemaLocation for import of http://mid.swisscom.ch/TS102204/as/v1.0; compilation may fail
[WARN] No schemaLocation for import of http://uri.etsi.org/TS102204/v1.1.2#; compilation may fail
[WARN] No schemaLocation for import of http://www.w3.org/2003/05/soap-envelope; compilation may fail
[WARN] No schemaLocation for import of http://www.w3.org/2000/09/xmldsig#; compilation may fail
[WARN] No schemaLocation for import of http://www.w3.org/2001/04/xmlenc#; compilation may fail
[WARN] No schemaLocation for import of http://www.swisscom.ch/TS102204/ext/v1.0.0; compilation may fail
...
Retrieving document at 'file:///home/hauser/mobileIdShellScripts/mobileid.wsdl'.
[WARN] No schemaLocation for import of http://www.w3.org/2000/09/xmldsig#; compilation may fail
[WARN] No schemaLocation for import of http://mid.swisscom.ch/TS102204/as/v1.0; compilation may fail
[WARN] No schemaLocation for import of http://uri.etsi.org/TS102204/v1.1.2#; compilation may fail
[WARN] No schemaLocation for import of http://www.w3.org/2003/05/soap-envelope; compilation may fail
[WARN] No schemaLocation for import of http://www.w3.org/2000/09/xmldsig#; compilation may fail
[WARN] No schemaLocation for import of http://www.w3.org/2001/04/xmlenc#; compilation may fail
[WARN] No schemaLocation for import of http://www.swisscom.ch/TS102204/ext/v1.0.0; compilation may fail

**Comment by phaupt** [comment]
I've tried with latest apache cxf version 3.2.7 (as recommended in the README) and it successfully created all stub files.

```$ ./apache-cxf-3.2.7/bin/wsdl2java -d src -b ./bindings.xml ./mobileid.wsdl```

However, with Axis2's wsdl2java it won't work. And this is a bit odd. We will investigate this...

**Comment by phaupt** [comment]
`MSS_FaultMessage` and `FaultParts` had to be removed, see latest `mobileid.wsdl`.
It seems to work with Axis2.
```
$ ./axis2-1.7.9/bin/wsdl2java.sh -uri ./mobileid.wsdl -o src-axis2 -EbindingFile ./bindings.xml
```
