### ISSUE TITLE
minimum version of saaj.jar ?

### ISSUE THREAD

**Issue by ralfhauser** [phaupt/mobileid-java#2]
in https://github.com/phaupt/mobileid-java/blob/master/client-saaj/README.md please specify a recommended version 

(the saaj.jar from 2005 doesn't   ;)  )

**Comment by phaupt** [comment]
Latest Java SDK and things should work just fine.
No need to use any 3rd party libraries like Axis.

https://en.wikipedia.org/wiki/Java_Web_Services_Development_Pack
https://docs.oracle.com/javaee/5/tutorial/doc/bnbhg.html
